import React, { Component } from 'react'
import {Link} from 'react-router-dom'
import './Styles.css'
import AlertDialog from './Dialog'
import OdsIcon from '../../assets/resize-icons/ods16.png'

const number = 16

const firstTopic = ['•	RESPEITE AS PESSOAS QUE PENSAM E ACREDITAM EM COISAS DIFERENTES DAS SUAS','•	SE ALGUÉM TE ABORRECER, NÃO BRIGUE. TENTE CONVERSAR COM QUEM TE ABORRECEU OU CONTE PARA OS SEUS PAIS OU PROFESSORES','•	SE VOCÊ VER ALGUÉM FAZENDO CHACOTA OU AMEAÇANDO UM AMIGO OU COLEGA, CONVERSE COM OS SEUS PAIS E PROFESSORES','•	FIQUE LONGE DAS DROGAS, A MAIORIA DAS MORTES VIOLENTAS ESTÃO DIRETAMENTE LIGADAS AO USO DE DROGAS.']
const secondTopic = ['•	REALIZAR PALESTRA SOBRE O RELACIONAMENTOS, PREVENÇÃO A VIOLÊNCIA E CUIDADOS NO TRÂNSITO.','•	PARTICIPAR DE ESPAÇOS COMO CONSELHO TUTELAR E CONSELHOS DE DIREITOS NO SEU MUNICÍPIO','•	REALIZAR CAMAPANHAS DE CULTURA DA PAZ, SENSIBILIZAÇÃO E COMBATE Á VIOLÊNCIA DOMÉSTICA, ABUSO SEXUAL E TRÁFICO HUMANO','•	DENUNCIAR CAOS DE VIOLÊNCIA CONTRA A MULHER, IDOSOS E CRIANÇAS','•	COMBATER A CORRUPÇÃO EM TODOS OS NÍVEIS','•	PROMOVER O ACESSO A ESPAÇO CULTURAL E ARTÍSTICO PARA A POPULAÇÃO JOVEM.','•	APOIAR O FUNCIONAMENTO OU INSTALAÇÃO DE UM CENTRO DE AÇÃO VOLUNTÁRIA NA SUA CIDADE.','•	FORTALECER AS INSTITUIÇÕES EFICAZES, RESPONSÁVEIS E TRANSPARENTES ','•	IMPLANTAR SISTEMAS DE MONITORAMENTO DOS GASTOS E INVESTIMENTOS PÚBLICOS, COMO OS PORTAIS DA TRANSPARÊNCIA E OBSERVATÓRIOS SOCIAIS','•	COMBATER O CRIME ORGANIZADO E REDUZIR O TRÁFICO DE ARMAS ILEGAIS.','•	PROMOVER E FAZER CUMPRIR LEIS E POLÍTICAS NÃO DISCRIMINATÓRIAS PARA O DESENVOLVIMENTO SUSTENTÁVEL']
const thirdTopic = []
const fourthTopic = []

export default class Ods_16 extends Component {
  render() {
    return (
        <div className="envolve-main">
          <div className="envolve-ods">
            <div className="ods-grande angulo-16"/>
            <div className="texto-ods texto-color-16">
              <h1>16 - Paz, Justiça e Instituições eficazes</h1>
              <p>
                VOCÊ SABIA QUE AS BRIGAS COMEÇAM PORQUE AS PESSOAS NÃO SE ENTENDEM OU NÃO GOSTAM DE QUEM TEM IDEIAS DIFERENTES? <br/><br/>
                ALGUMAS PESSOAS FICAM FAZENDO ALGUMAS BRINCADEIRAS CHATAS COM AS OUTRAS SÓ PORQUE SÃO DIFERENTES, MAS NÓS SABEMOS
                QUE SER DIFERENTE É MUITO LEGAL.<br/><br/>
                E QUANDO ESSAS PESSOAS SÃO LÍDERES DE PAÍSES E NÃO RESPEITAM COMO OUTROS PAÍSES CUIDAM DO SEU POVO, ELAS BRIGAM E SURGEM AS GUERRAS.<br/><br/>
                JÁ IMAGINOU QUE CHATO SERIA SE TODO MUNDO FOSSE IGUAL? POR EXEMPLO, SE TODO MUNDO TORCESSE PARA O MESMO TIME, NÃO EXISTIRIAM OS CAMPEONATOS COMO A COPA DO MUNDO E AS OLIMPÍADAS.<br/><br/>
                POR ISSO PRECISAMOS SEMPRE ACEITAR E RESPEITAR AS DIFERENÇAS PARA VIVERMOS NUM MUNDO EM PAZ!
              </p>
              </div>
          </div>
          <div className="envolve-button-ods">
          <AlertDialog  odsIcon={OdsIcon} number={number} firstTopic={firstTopic} secondTopic={secondTopic} thirdTopic={thirdTopic} fourthTopic={fourthTopic} />
            <Link to="/Home" className="button-ods button-color-16" style={{ textDecoration: 'none' }}>Voltar para as ODS</Link>
          </div>
        </div>
    )
  }
}


